name: Build and Deploy

on:
    push:
        branches: [master]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4
            - name: Build and Deploy
              uses: rreichel3/vuepress-github-actions-deploy@master
              env:
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  BUILD_DIR: dist/
                  BUILD_SCRIPT: yarn install && yarn build
                  PAGES_CNAME: d3sox.me
